name: Test Build

on: 
  workflow_dispatch:
   inputs:
      device:
        description: 'Select device'     
        required: true
        type: choice
        options:
        - AX1800
        - AXT1800
        - MT2500
        - MT3000
        - SF1200
        - SFT1200 
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: build ipk
      id: build
      run: |
        ls
        description: 'Source code URL'     
        
