name: Test Build

on: 
  workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: build ipk
      id: build
      run: |
        ls
        description: 'Source code URL'     
        
